// Dialect test-database factory: runs the test suite against a live
// MySQL or PostgreSQL server instead of in-memory SQLite.
//
// Each call provisions a dedicated database on the target server (unique
// name, full migration run, dropped on test cleanup), so tests get the same
// fresh-schema isolation the in-memory SQLite factory provides.
package testutil

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"net/url"
	"testing"

	"github.com/go-sql-driver/mysql"

	"github.com/babykart/gozone/internal/config"
	"github.com/babykart/gozone/internal/database"
)

// mysqlDSNWithDB returns the given go-sql-driver DSN with its database name
// replaced by db.
func mysqlDSNWithDB(dsn, db string) (string, error) {
	cfg, err := mysql.ParseDSN(dsn)
	if err != nil {
		return "", fmt.Errorf("parse MySQL DSN: %w", err)
	}
	cfg.DBName = db
	return cfg.FormatDSN(), nil
}

// postgresDSNWithDB returns the given PostgreSQL DSN with its database name
// replaced by db. URL-style DSNs (postgres://…) are rewritten via net/url;
// lib/pq also accepts key=value strings, but rewriting those reliably (the
// dbname key may be absent, present, or quoted) is not worth the complexity —
// pass a URL-form DSN instead.
func postgresDSNWithDB(dsn, db string) (string, error) {
	u, err := url.Parse(dsn)
	if err != nil {
		return "", fmt.Errorf("parse PostgreSQL DSN: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("postgres DSN must be URL-style (postgres://user:pass@host:port/db), got %q", dsn)
	}
	u.Path = "/" + db
	return u.String(), nil
}

// randomDBName generates a unique, lower-case identifier safe for both MySQL
// (64-byte limit) and PostgreSQL (63-byte limit) without quoting.
func randomDBName(prefix string) (string, error) {
	var buf [8]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", fmt.Errorf("generate database name: %w", err)
	}
	return prefix + hex.EncodeToString(buf[:]), nil
}

// NewTestDBDialect creates a test database on a live server identified by
// driver and dsn ("mysql" or "postgres"/"postgresql"; the DSN points at any
// existing database the credentials may reach, e.g. the server's maintenance
// database). It connects to that server, creates a uniquely named database,
// runs the full GoZone migrations on it, and returns a ready-to-use handle.
//
// The created database (and only it) is dropped when the test finishes via
// t.Cleanup, so every test starts from a pristine schema — the same isolation
// guarantee NewTestDB gives with in-memory SQLite, which remains the default
// for local runs.
func NewTestDBDialect(t *testing.T, driver, dsn string) *database.DB {
	t.Helper()

	// Raw driver names for the administrative connection (CREATE/DROP
	// DATABASE). No time values are scanned there, so the dialect's DSN
	// normalization (parseTime etc.) is not needed; database.New applies it
	// to the actual test connection below.
	var adminDriver string
	var withDB func(dsn, db string) (string, error)
	switch driver {
	case "mysql", "mariadb":
		adminDriver = "mysql"
		withDB = mysqlDSNWithDB
	case "postgres", "postgresql":
		adminDriver = "postgres"
		withDB = postgresDSNWithDB
	default:
		t.Fatalf("unsupported dialect test driver %q (use mysql or postgres)", driver)
	}

	name, err := randomDBName("gozone_test_")
	if err != nil {
		t.Fatal(err)
	}

	// CREATE/DROP DATABASE cannot use query placeholders on any driver; the
	// identifier is generated by randomDBName (hex only), never from caller
	// input.
	admin, err := sql.Open(adminDriver, dsn)
	if err != nil {
		t.Fatalf("open admin connection: %v", err)
	}
	if _, err := admin.Exec(fmt.Sprintf("CREATE DATABASE %s", name)); err != nil { // #nosec G201 -- name is crypto/rand hex, not user input; identifiers cannot be parameterized
		t.Fatalf("create database %s: %v", name, err)
	}
	if err := admin.Close(); err != nil { // #nosec G104 -- best-effort cleanup, creation already succeeded
		t.Logf("close admin connection: %v", err)
	}
	t.Cleanup(func() {
		drop, err := sql.Open(adminDriver, dsn)
		if err != nil {
			t.Logf("open drop connection for %s: %v", name, err)
			return
		}
		defer drop.Close()                                                                    // #nosec G104 -- best-effort cleanup
		if _, err := drop.Exec(fmt.Sprintf("DROP DATABASE IF EXISTS %s", name)); err != nil { // #nosec G201 -- name is crypto/rand hex, not user input; identifiers cannot be parameterized
			t.Logf("drop database %s: %v", name, err)
		}
	})

	testDSN, err := withDB(dsn, name)
	if err != nil {
		t.Fatal(err)
	}
	db, err := database.New(&config.DatabaseConfig{Driver: driver, DSN: testDSN})
	if err != nil {
		t.Fatalf("open %s test database: %v", driver, err)
	}
	t.Cleanup(func() { db.Close() }) // #nosec G104
	return db
}
